services:
  - type: web
    name: medusa-backend
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 9000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: medusa-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: medusa-redis
          type: redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: MEDUSA_BACKEND_URL
        value: https://medusa-backend.onrender.com
      - key: MEDUSA_ADMIN_CORS
        value: https://medusa-frontend-pages.pages.dev,https://localhost:3000
      - key: MEDUSA_STORE_CORS
        value: https://medusa-frontend-pages.pages.dev,https://localhost:3000
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: your-email@gmail.com
      - key: SMTP_PASS
        value: your-app-password
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: SEED_DATABASE
        value: false
    healthCheckPath: /health

databases:
  - name: medusa-postgres
    plan: free
    region: oregon

redis:
  - name: medusa-redis
    plan: free

