name = "medusa-backend"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "medusa-backend-prod"

# 环境变量
[vars]
NODE_ENV = "production"

# 数据库连接 (需要配置外部数据库)
# [secrets]
# DATABASE_URL = "your-database-url"
# REDIS_URL = "your-redis-url"
# JWT_SECRET = "your-jwt-secret"
# COOKIE_SECRET = "your-cookie-secret"
# ENCRYPTION_KEY = "your-encryption-key"

# KV存储 (用于缓存)
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"
